### ISSUE TITLE
Add a global keyboard shortcut

### ISSUE THREAD

**Issue by zeke** [muan/confetti#2]
I love this app!

I wanna throw confetti without clicking the :cat2:. This could be done with a global shortcut, and/or when the already-running app is invoked (with spotlight, etc) like https://github.com/muan/mojibar/pull/36

**Comment by muan** [comment]
Any ideas on what the shortcut should be defaulted to? (at this point I feel like they should always be customisable. :joy:)

**Comment by zeke** [comment]
How about <kbd>CmdOrCtrl+Shift+1</kbd>, as in a modified exclamation point.

**Comment by muan** [comment]
:tada: https://github.com/muan/confetti/releases/tag/0.0.3

**Comment by zeke** [comment]
It works!
